import Foundation

// MARK: - App String Keys

enum AppString: String {
    // Home
    case appName = "app_name"
    case howAreYouFeeling = "how_are_you_feeling"
    case howIFeel = "how_i_feel"
    case whatImDoing = "what_im_doing"
    case dayStreak = "day_streak"
    case keepGoing = "keep_going"

    // Tabs
    case tabHome = "tab_home"
    case tabFavorites = "tab_favorites"
    case tabHistory = "tab_history"
    case tabSettings = "tab_settings"

    // Dhikir Display
    case translation = "translation"
    case benefit = "benefit"
    case tapToCount = "tap_to_count"
    case completed = "completed"
    case listenToRecitation = "listen_to_recitation"
    case swipeToNavigate = "swipe_to_navigate"
    case noDhikirsFound = "no_dhikirs_found"
    case goBack = "go_back"
    case shareDhikir = "share_dhikir"
    case addToFavorites = "add_to_favorites"
    case removeFromFavorites = "remove_from_favorites"
    case ofCount = "of_count" // "X of Y"
    case previous = "previous"
    case next = "next"
    case clickOrSpaceToCount = "click_or_space_to_count"

    // Favorites
    case noFavoritesYet = "no_favorites_yet"
    case favoritesHint = "favorites_hint"
    case dhikirDetails = "dhikir_details"
    case repeatTimes = "repeat_times"

    // History
    case noHistoryYet = "no_history_yet"
    case historyHint = "history_hint"
    case clear = "clear"
    case clearHistory = "clear_history"
    case clearHistoryWarning = "clear_history_warning"
    case today = "today"
    case yesterday = "yesterday"

    // Settings
    case settings = "settings"
    case preferences = "preferences"
    case yourProgress = "your_progress"
    case currentStreak = "current_streak"
    case longestStreak = "longest_streak"
    case totalDays = "total_days"
    case notifications = "notifications"
    case enableNotifications = "enable_notifications"
    case appearance = "appearance"
    case appearanceSystem = "appearance_system"
    case appearanceLight = "appearance_light"
    case appearanceDark = "appearance_dark"
    case feedback = "feedback"
    case hapticFeedback = "haptic_feedback"
    case translationLanguage = "translation_language"
    case about = "about"
    case version = "version"
    case dhikirs = "dhikirs"
    case sources = "sources"
    case quranAndHadith = "quran_and_hadith"
    case languages = "languages"
    case legal = "legal"
    case disclaimer = "disclaimer"
    case disclaimerNote = "disclaimer_note"
    case data = "data"
    case resetAllData = "reset_all_data"
    case cancel = "cancel"
    case reset = "reset"
    case resetWarning = "reset_warning"
    case done = "done"
    case selectTime = "select_time"

    // Share
    case shareDhikirTitle = "share_dhikir_title"
    case copyText = "copy_text"
    case shareVia = "share_via"

    // Onboarding
    case salaam = "salaam"
    case salaamArabic = "salaam_arabic"
    case welcomeDescription = "welcome_description"
    case howAreYouFeelingTitle = "how_are_you_feeling_title"
    case howAreYouFeelingArabic = "how_are_you_feeling_arabic"
    case howAreYouFeelingDescription = "how_are_you_feeling_description"
    case gentleReminders = "gentle_reminders"
    case gentleRemindersArabic = "gentle_reminders_arabic"
    case gentleRemindersDescription = "gentle_reminders_description"
    case buildYourPractice = "build_your_practice"
    case buildYourPracticeArabic = "build_your_practice_arabic"
    case buildYourPracticeDescription = "build_your_practice_description"
    case chooseYourLanguage = "choose_your_language"
    case chooseLanguageDescription = "choose_language_description"
    case beginYourJourney = "begin_your_journey"
    case enableNotificationsButton = "enable_notifications_button"
    case notificationDeniedMessage = "notification_denied_message"
    case continueButton = "continue_button"
    case skip = "skip"
    case previousButton = "previous_button"

    // Emotional States
    case emotionAnxious = "emotion_anxious"
    case emotionSad = "emotion_sad"
    case emotionAngry = "emotion_angry"
    case emotionGrateful = "emotion_grateful"
    case emotionHopeful = "emotion_hopeful"
    case emotionLonely = "emotion_lonely"
    case emotionOverwhelmed = "emotion_overwhelmed"
    case emotionFearful = "emotion_fearful"
    case emotionJoyful = "emotion_joyful"
    case emotionLost = "emotion_lost"

    // Emotional Descriptions
    case emotionAnxiousDesc = "emotion_anxious_desc"
    case emotionSadDesc = "emotion_sad_desc"
    case emotionAngryDesc = "emotion_angry_desc"
    case emotionGratefulDesc = "emotion_grateful_desc"
    case emotionHopefulDesc = "emotion_hopeful_desc"
    case emotionLonelyDesc = "emotion_lonely_desc"
    case emotionOverwhelmedDesc = "emotion_overwhelmed_desc"
    case emotionFearfulDesc = "emotion_fearful_desc"
    case emotionJoyfulDesc = "emotion_joyful_desc"
    case emotionLostDesc = "emotion_lost_desc"

    // Life Situations
    case situationUponWaking = "situation_upon_waking"
    case situationDuringIllness = "situation_during_illness"
    case situationTraveling = "situation_traveling"
    case situationFacingDifficulty = "situation_facing_difficulty"
    case situationBeforeDecision = "situation_before_decision"
    case situationSeekingForgiveness = "situation_seeking_forgiveness"

    // Life Situation Descriptions
    case situationUponWakingDesc = "situation_upon_waking_desc"
    case situationDuringIllnessDesc = "situation_during_illness_desc"
    case situationTravelingDesc = "situation_traveling_desc"
    case situationFacingDifficultyDesc = "situation_facing_difficulty_desc"
    case situationBeforeDecisionDesc = "situation_before_decision_desc"
    case situationSeekingForgivenessDesc = "situation_seeking_forgiveness_desc"
}

// MARK: - Localization Service

struct LocalizationService {
    static let shared = LocalizationService()

    private let translations: [SupportedLanguage: [String: String]] = [
        .english: [
            // Home
            "app_name": "Dhikir",
            "how_are_you_feeling": "How are you feeling?",
            "how_i_feel": "How I Feel",
            "what_im_doing": "What I'm Doing",
            "day_streak": "Day Streak",
            "keep_going": "Keep going!",

            // Tabs
            "tab_home": "Home",
            "tab_favorites": "Favorites",
            "tab_history": "History",
            "tab_settings": "Settings",

            // Dhikir Display
            "translation": "Translation",
            "benefit": "Benefit",
            "tap_to_count": "Tap to Count",
            "completed": "Completed!",
            "listen_to_recitation": "Listen to Recitation",
            "swipe_to_navigate": "Swipe to navigate",
            "no_dhikirs_found": "No dhikirs found",
            "go_back": "Go Back",
            "share_dhikir": "Share dhikir",
            "add_to_favorites": "Add to favorites",
            "remove_from_favorites": "Remove from favorites",
            "of_count": "of",
            "previous": "Previous",
            "next": "Next",
            "click_or_space_to_count": "Click anywhere or press Space to count",

            // Favorites
            "no_favorites_yet": "No Favorites Yet",
            "favorites_hint": "Dhikirs you love will appear here.\nTap the heart icon to save them.",
            "dhikir_details": "Dhikir Details",
            "repeat_times": "time(s)",

            // History
            "no_history_yet": "No History Yet",
            "history_hint": "Your reading history will appear here\nas you explore dhikirs.",
            "clear": "Clear",
            "clear_history": "Clear History",
            "clear_history_warning": "This will delete all your reading history. This action cannot be undone.",
            "today": "Today",
            "yesterday": "Yesterday",

            // Settings
            "settings": "Settings",
            "preferences": "Preferences",
            "your_progress": "Your Progress",
            "current_streak": "Current Streak",
            "longest_streak": "Longest Streak",
            "total_days": "Total Days",
            "notifications": "Notifications",
            "enable_notifications": "Enable Notifications",
            "appearance": "Appearance",
            "appearance_system": "System",
            "appearance_light": "Light",
            "appearance_dark": "Dark",
            "feedback": "Feedback",
            "haptic_feedback": "Haptic Feedback",
            "translation_language": "Translation Language",
            "about": "About",
            "version": "Version",
            "dhikirs": "Dhikirs",
            "sources": "Sources",
            "quran_and_hadith": "Quran & Hadith",
            "languages": "Languages",
            "legal": "Legal",
            "disclaimer": "Disclaimer",
            "disclaimer_note": "This app is for educational and spiritual purposes only. Content should be verified with qualified Islamic scholars.",
            "data": "Data",
            "reset_all_data": "Reset All Data",
            "cancel": "Cancel",
            "reset": "Reset",
            "reset_warning": "This will delete all your favorites, history, and streak progress. This action cannot be undone.",
            "done": "Done",
            "select_time": "Set Time",

            // Share
            "share_dhikir_title": "Share Dhikir",
            "copy_text": "Copy Text",
            "share_via": "Share via...",

            // Onboarding
            "salaam": "Salaam",
            "salaam_arabic": "السلام عليكم",
            "welcome_description": "Welcome to Dhikir, your companion for remembrance of Allah throughout the day.",
            "how_are_you_feeling_title": "How Are You Feeling?",
            "how_are_you_feeling_arabic": "كيف حالك",
            "how_are_you_feeling_description": "Tell us your emotional state or what you're doing, and we'll show you relevant dhikirs from the Quran and Sunnah.",
            "gentle_reminders": "Gentle Reminders",
            "gentle_reminders_arabic": "تذكير لطيف",
            "gentle_reminders_description": "Receive warm, personal notifications throughout the day asking how you're feeling.",
            "build_your_practice": "Build Your Practice",
            "build_your_practice_arabic": "بناء ممارستك",
            "build_your_practice_description": "Track your daily streak, save favorites, and build a consistent habit of remembrance.",
            "choose_your_language": "Choose Your Language",
            "choose_language_description": "Select the language you'd like to use. You can change this anytime in Settings.",
            "begin_your_journey": "Begin Your Journey",
            "enable_notifications_button": "Enable Notifications",
            "notification_denied_message": "No worries — you can enable this later in Settings.",
            "continue_button": "Continue",
            "skip": "Skip",
            "previous_button": "Previous",

            // Emotional States
            "emotion_anxious": "Anxious",
            "emotion_sad": "Sad",
            "emotion_angry": "Angry",
            "emotion_grateful": "Grateful",
            "emotion_hopeful": "Hopeful",
            "emotion_lonely": "Lonely",
            "emotion_overwhelmed": "Overwhelmed",
            "emotion_fearful": "Fearful",
            "emotion_joyful": "Joyful",
            "emotion_lost": "Lost",

            // Emotional Descriptions
            "emotion_anxious_desc": "Find peace and tranquility",
            "emotion_sad_desc": "Seek comfort and hope",
            "emotion_angry_desc": "Find calm and patience",
            "emotion_grateful_desc": "Express your thankfulness",
            "emotion_hopeful_desc": "Strengthen your trust",
            "emotion_lonely_desc": "Remember Allah's companionship",
            "emotion_overwhelmed_desc": "Find ease and relief",
            "emotion_fearful_desc": "Seek protection and courage",
            "emotion_joyful_desc": "Share your happiness",
            "emotion_lost_desc": "Seek guidance and clarity",

            // Life Situations
            "situation_upon_waking": "Upon Waking",
            "situation_during_illness": "During Illness",
            "situation_traveling": "Traveling",
            "situation_facing_difficulty": "Facing Difficulty",
            "situation_before_decision": "Before a Decision",
            "situation_seeking_forgiveness": "Seeking Forgiveness",

            // Life Situation Descriptions
            "situation_upon_waking_desc": "Thank Allah for a new day",
            "situation_during_illness_desc": "Seek healing and patience",
            "situation_traveling_desc": "Protection for your journey",
            "situation_facing_difficulty_desc": "Strength through hardship",
            "situation_before_decision_desc": "Seek divine guidance",
            "situation_seeking_forgiveness_desc": "Return to Allah",
        ],

        .arabic: [
            "app_name": "ذكر",
            "how_are_you_feeling": "كيف حالك؟",
            "how_i_feel": "ما أشعر به",
            "what_im_doing": "ما أفعله",
            "day_streak": "أيام متتالية",
            "keep_going": "استمر!",
            "tab_home": "الرئيسية",
            "tab_favorites": "المفضلة",
            "tab_history": "السجل",
            "tab_settings": "الإعدادات",
            "translation": "الترجمة",
            "benefit": "الفائدة",
            "tap_to_count": "اضغط للعد",
            "completed": "اكتمل!",
            "listen_to_recitation": "استمع للتلاوة",
            "swipe_to_navigate": "اسحب للتنقل",
            "no_dhikirs_found": "لا توجد أذكار",
            "go_back": "رجوع",
            "share_dhikir": "مشاركة الذكر",
            "add_to_favorites": "إضافة للمفضلة",
            "remove_from_favorites": "إزالة من المفضلة",
            "of_count": "من",
            "previous": "السابق",
            "next": "التالي",
            "click_or_space_to_count": "انقر في أي مكان أو اضغط مسافة للعد",
            "no_favorites_yet": "لا توجد مفضلة بعد",
            "favorites_hint": "الأذكار المفضلة ستظهر هنا.\nاضغط على أيقونة القلب لحفظها.",
            "dhikir_details": "تفاصيل الذكر",
            "repeat_times": "مرة/مرات",
            "no_history_yet": "لا يوجد سجل بعد",
            "history_hint": "سيظهر سجل قراءتك هنا\nعند تصفح الأذكار.",
            "clear": "مسح",
            "clear_history": "مسح السجل",
            "clear_history_warning": "سيؤدي هذا إلى حذف سجل القراءة بالكامل. لا يمكن التراجع عن هذا الإجراء.",
            "today": "اليوم",
            "yesterday": "أمس",
            "settings": "الإعدادات",
            "preferences": "التفضيلات",
            "your_progress": "تقدمك",
            "current_streak": "السلسلة الحالية",
            "longest_streak": "أطول سلسلة",
            "total_days": "إجمالي الأيام",
            "notifications": "الإشعارات",
            "enable_notifications": "تفعيل الإشعارات",
            "appearance": "المظهر",
            "appearance_system": "النظام",
            "appearance_light": "فاتح",
            "appearance_dark": "داكن",
            "feedback": "الاستجابة",
            "haptic_feedback": "الاستجابة اللمسية",
            "translation_language": "لغة الترجمة",
            "about": "حول",
            "version": "الإصدار",
            "dhikirs": "أذكار",
            "sources": "المصادر",
            "quran_and_hadith": "القرآن والحديث",
            "languages": "اللغات",
            "legal": "قانوني",
            "disclaimer": "إخلاء المسؤولية",
            "disclaimer_note": "هذا التطبيق لأغراض تعليمية وروحية فقط. يجب التحقق من المحتوى مع علماء إسلاميين مؤهلين.",
            "data": "البيانات",
            "reset_all_data": "إعادة تعيين جميع البيانات",
            "cancel": "إلغاء",
            "reset": "إعادة تعيين",
            "reset_warning": "سيؤدي هذا إلى حذف جميع المفضلة والسجل وتقدم السلسلة. لا يمكن التراجع عن هذا الإجراء.",
            "done": "تم",
            "select_time": "تحديد الوقت",
            "share_dhikir_title": "مشاركة ذكر",
            "copy_text": "نسخ النص",
            "share_via": "مشاركة عبر...",
            "salaam": "سلام",
            "salaam_arabic": "السلام عليكم",
            "welcome_description": "مرحباً بك في ذكر، رفيقك لذكر الله طوال اليوم.",
            "how_are_you_feeling_title": "كيف حالك؟",
            "how_are_you_feeling_arabic": "كيف حالك",
            "how_are_you_feeling_description": "أخبرنا بحالتك النفسية أو ما تفعله، وسنعرض لك أذكاراً من القرآن والسنة.",
            "gentle_reminders": "تذكيرات لطيفة",
            "gentle_reminders_arabic": "تذكير لطيف",
            "gentle_reminders_description": "تلقَّ إشعارات دافئة طوال اليوم تسألك عن حالك.",
            "build_your_practice": "ابنِ عادتك",
            "build_your_practice_arabic": "بناء ممارستك",
            "build_your_practice_description": "تتبع سلسلتك اليومية، احفظ المفضلة، وابنِ عادة ذكر مستمرة.",
            "choose_your_language": "اختر لغتك",
            "choose_language_description": "اختر اللغة التي تريد استخدامها. يمكنك تغييرها في أي وقت من الإعدادات.",
            "begin_your_journey": "ابدأ رحلتك",
            "enable_notifications_button": "تفعيل الإشعارات",
            "notification_denied_message": "لا بأس — يمكنك تفعيل هذا لاحقاً من الإعدادات.",
            "continue_button": "متابعة",
            "skip": "تخطي",
            "previous_button": "السابق",
            "emotion_anxious": "قلق",
            "emotion_sad": "حزين",
            "emotion_angry": "غاضب",
            "emotion_grateful": "شاكر",
            "emotion_hopeful": "متفائل",
            "emotion_lonely": "وحيد",
            "emotion_overwhelmed": "مرهق",
            "emotion_fearful": "خائف",
            "emotion_joyful": "فرحان",
            "emotion_lost": "تائه",
            "emotion_anxious_desc": "اعثر على السكينة والطمأنينة",
            "emotion_sad_desc": "اطلب الراحة والأمل",
            "emotion_angry_desc": "اعثر على الهدوء والصبر",
            "emotion_grateful_desc": "عبّر عن شكرك",
            "emotion_hopeful_desc": "قوِّ توكلك",
            "emotion_lonely_desc": "تذكر معية الله",
            "emotion_overwhelmed_desc": "اعثر على اليسر والراحة",
            "emotion_fearful_desc": "اطلب الحماية والشجاعة",
            "emotion_joyful_desc": "شارك سعادتك",
            "emotion_lost_desc": "اطلب الهداية والوضوح",
            "situation_upon_waking": "عند الاستيقاظ",
            "situation_during_illness": "عند المرض",
            "situation_traveling": "السفر",
            "situation_facing_difficulty": "عند الشدة",
            "situation_before_decision": "قبل القرار",
            "situation_seeking_forgiveness": "الاستغفار",
            "situation_upon_waking_desc": "اشكر الله على يوم جديد",
            "situation_during_illness_desc": "اطلب الشفاء والصبر",
            "situation_traveling_desc": "حماية لرحلتك",
            "situation_facing_difficulty_desc": "القوة في الشدة",
            "situation_before_decision_desc": "اطلب الهداية الربانية",
            "situation_seeking_forgiveness_desc": "العودة إلى الله",
        ],

        .urdu: [
            "app_name": "ذکر",
            "how_are_you_feeling": "آپ کیسا محسوس کر رہے ہیں؟",
            "how_i_feel": "میں کیسا محسوس کرتا ہوں",
            "what_im_doing": "میں کیا کر رہا ہوں",
            "day_streak": "مسلسل دن",
            "keep_going": "جاری رکھیں!",
            "tab_home": "ہوم",
            "tab_favorites": "پسندیدہ",
            "tab_history": "تاریخ",
            "tab_settings": "ترتیبات",
            "translation": "ترجمہ",
            "benefit": "فائدہ",
            "tap_to_count": "گننے کے لیے ٹیپ کریں",
            "completed": "مکمل!",
            "listen_to_recitation": "تلاوت سنیں",
            "swipe_to_navigate": "نیویگیٹ کرنے کے لیے سوائپ کریں",
            "no_dhikirs_found": "کوئی اذکار نہیں ملے",
            "go_back": "واپس جائیں",
            "share_dhikir": "ذکر شیئر کریں",
            "add_to_favorites": "پسندیدہ میں شامل کریں",
            "remove_from_favorites": "پسندیدہ سے ہٹائیں",
            "of_count": "میں سے",
            "previous": "پچھلا",
            "next": "اگلا",
            "click_or_space_to_count": "گننے کے لیے کہیں بھی کلک کریں یا اسپیس دبائیں",
            "no_favorites_yet": "ابھی تک کوئی پسندیدہ نہیں",
            "favorites_hint": "آپ کے پسندیدہ اذکار یہاں نظر آئیں گے۔\nانہیں محفوظ کرنے کے لیے دل کے آئیکن پر ٹیپ کریں۔",
            "dhikir_details": "ذکر کی تفصیلات",
            "repeat_times": "مرتبہ",
            "no_history_yet": "ابھی تک کوئی تاریخ نہیں",
            "history_hint": "اذکار پڑھنے کی تاریخ یہاں\nنظر آئے گی۔",
            "clear": "صاف کریں",
            "clear_history": "تاریخ صاف کریں",
            "clear_history_warning": "اس سے آپ کی پوری پڑھنے کی تاریخ حذف ہو جائے گی۔ یہ عمل واپس نہیں ہو سکتا۔",
            "today": "آج",
            "yesterday": "کل",
            "settings": "ترتیبات",
            "preferences": "ترجیحات",
            "your_progress": "آپ کی پیشرفت",
            "current_streak": "موجودہ سلسلہ",
            "longest_streak": "طویل ترین سلسلہ",
            "total_days": "کل دن",
            "notifications": "اطلاعات",
            "enable_notifications": "اطلاعات فعال کریں",
            "appearance": "ظاہری شکل",
            "appearance_system": "سسٹم",
            "appearance_light": "ہلکا",
            "appearance_dark": "گہرا",
            "feedback": "فیڈبیک",
            "haptic_feedback": "ہیپٹک فیڈبیک",
            "translation_language": "ترجمے کی زبان",
            "about": "تعارف",
            "version": "ورژن",
            "dhikirs": "اذکار",
            "sources": "ذرائع",
            "quran_and_hadith": "قرآن و حدیث",
            "languages": "زبانیں",
            "legal": "قانونی",
            "disclaimer": "دستبرداری",
            "disclaimer_note": "یہ ایپ صرف تعلیمی اور روحانی مقاصد کے لیے ہے۔ مواد کی تصدیق مستند اسلامی علماء سے کی جانی چاہیے۔",
            "data": "ڈیٹا",
            "reset_all_data": "تمام ڈیٹا ری سیٹ کریں",
            "cancel": "منسوخ",
            "reset": "ری سیٹ",
            "reset_warning": "اس سے آپ کے تمام پسندیدہ، تاریخ، اور سلسلے کی پیشرفت حذف ہو جائے گی۔ یہ عمل واپس نہیں ہو سکتا۔",
            "done": "مکمل",
            "select_time": "وقت مقرر کریں",
            "share_dhikir_title": "ذکر شیئر کریں",
            "copy_text": "متن کاپی کریں",
            "share_via": "شیئر کریں بذریعہ...",
            "salaam": "سلام",
            "salaam_arabic": "السلام علیکم",
            "welcome_description": "ذکر میں خوش آمدید، دن بھر اللہ کی یاد کے لیے آپ کا ساتھی۔",
            "how_are_you_feeling_title": "آپ کیسا محسوس کر رہے ہیں؟",
            "how_are_you_feeling_arabic": "کیف حالک",
            "how_are_you_feeling_description": "ہمیں اپنی جذباتی کیفیت بتائیں، اور ہم آپ کو قرآن و سنت سے متعلقہ اذکار دکھائیں گے۔",
            "gentle_reminders": "نرم یاددہانیاں",
            "gentle_reminders_arabic": "تذکیر لطیف",
            "gentle_reminders_description": "دن بھر پیارے اطلاعات حاصل کریں جو آپ سے آپ کی حالت پوچھیں۔",
            "build_your_practice": "اپنی عادت بنائیں",
            "build_your_practice_arabic": "بناء ممارستک",
            "build_your_practice_description": "اپنے روزانہ سلسلے کو ٹریک کریں، پسندیدہ محفوظ کریں، اور ذکر کی مستقل عادت بنائیں۔",
            "choose_your_language": "اپنی زبان منتخب کریں",
            "choose_language_description": "وہ زبان منتخب کریں جو آپ استعمال کرنا چاہتے ہیں۔ آپ اسے کسی بھی وقت سیٹنگز میں تبدیل کر سکتے ہیں۔",
            "begin_your_journey": "اپنا سفر شروع کریں",
            "enable_notifications_button": "اطلاعات فعال کریں",
            "notification_denied_message": "کوئی بات نہیں — آپ اسے بعد میں سیٹنگز سے فعال کر سکتے ہیں۔",
            "continue_button": "جاری رکھیں",
            "skip": "چھوڑیں",
            "previous_button": "پچھلا",
            "emotion_anxious": "پریشان",
            "emotion_sad": "اداس",
            "emotion_angry": "ناراض",
            "emotion_grateful": "شکرگزار",
            "emotion_hopeful": "پرامید",
            "emotion_lonely": "تنہا",
            "emotion_overwhelmed": "مغلوب",
            "emotion_fearful": "خائف",
            "emotion_joyful": "خوش",
            "emotion_lost": "گمراہ",
            "emotion_anxious_desc": "سکون اور اطمینان پائیں",
            "emotion_sad_desc": "راحت اور امید تلاش کریں",
            "emotion_angry_desc": "صبر اور سکون پائیں",
            "emotion_grateful_desc": "اپنا شکر ادا کریں",
            "emotion_hopeful_desc": "اپنا توکل مضبوط کریں",
            "emotion_lonely_desc": "اللہ کی معیت یاد کریں",
            "emotion_overwhelmed_desc": "آسانی اور راحت پائیں",
            "emotion_fearful_desc": "حفاظت اور ہمت طلب کریں",
            "emotion_joyful_desc": "اپنی خوشی بانٹیں",
            "emotion_lost_desc": "ہدایت اور وضاحت طلب کریں",
            "situation_upon_waking": "جاگنے پر",
            "situation_during_illness": "بیماری میں",
            "situation_traveling": "سفر میں",
            "situation_facing_difficulty": "مشکل میں",
            "situation_before_decision": "فیصلے سے پہلے",
            "situation_seeking_forgiveness": "استغفار",
            "situation_upon_waking_desc": "نئے دن کے لیے اللہ کا شکر",
            "situation_during_illness_desc": "شفا اور صبر طلب کریں",
            "situation_traveling_desc": "سفر کی حفاظت",
            "situation_facing_difficulty_desc": "مشکل میں طاقت",
            "situation_before_decision_desc": "الہٰی رہنمائی طلب کریں",
            "situation_seeking_forgiveness_desc": "اللہ کی طرف رجوع",
        ],

        .indonesian: [
            "app_name": "Dhikir",
            "how_are_you_feeling": "Bagaimana perasaanmu?",
            "how_i_feel": "Perasaan Saya",
            "what_im_doing": "Yang Saya Lakukan",
            "day_streak": "Hari Berturut-turut",
            "keep_going": "Terus semangat!",
            "tab_home": "Beranda",
            "tab_favorites": "Favorit",
            "tab_history": "Riwayat",
            "tab_settings": "Pengaturan",
            "translation": "Terjemahan",
            "benefit": "Manfaat",
            "tap_to_count": "Ketuk untuk Menghitung",
            "completed": "Selesai!",
            "listen_to_recitation": "Dengarkan Bacaan",
            "swipe_to_navigate": "Geser untuk navigasi",
            "no_dhikirs_found": "Tidak ada dzikir ditemukan",
            "go_back": "Kembali",
            "share_dhikir": "Bagikan dzikir",
            "add_to_favorites": "Tambah ke favorit",
            "remove_from_favorites": "Hapus dari favorit",
            "of_count": "dari",
            "previous": "Sebelumnya",
            "next": "Selanjutnya",
            "click_or_space_to_count": "Klik di mana saja atau tekan Spasi untuk menghitung",
            "no_favorites_yet": "Belum Ada Favorit",
            "favorites_hint": "Dzikir favorit Anda akan muncul di sini.\nKetuk ikon hati untuk menyimpannya.",
            "dhikir_details": "Detail Dzikir",
            "repeat_times": "kali",
            "no_history_yet": "Belum Ada Riwayat",
            "history_hint": "Riwayat bacaan Anda akan muncul di sini\nsaat Anda menjelajahi dzikir.",
            "clear": "Hapus",
            "clear_history": "Hapus Riwayat",
            "clear_history_warning": "Ini akan menghapus semua riwayat bacaan Anda. Tindakan ini tidak dapat dibatalkan.",
            "today": "Hari Ini",
            "yesterday": "Kemarin",
            "settings": "Pengaturan",
            "preferences": "Preferensi",
            "your_progress": "Kemajuan Anda",
            "current_streak": "Streak Saat Ini",
            "longest_streak": "Streak Terpanjang",
            "total_days": "Total Hari",
            "notifications": "Notifikasi",
            "enable_notifications": "Aktifkan Notifikasi",
            "appearance": "Tampilan",
            "appearance_system": "Sistem",
            "appearance_light": "Terang",
            "appearance_dark": "Gelap",
            "feedback": "Umpan Balik",
            "haptic_feedback": "Umpan Balik Haptik",
            "translation_language": "Bahasa Terjemahan",
            "about": "Tentang",
            "version": "Versi",
            "dhikirs": "Dzikir",
            "sources": "Sumber",
            "quran_and_hadith": "Quran & Hadits",
            "languages": "Bahasa",
            "legal": "Hukum",
            "disclaimer": "Disclaimer",
            "disclaimer_note": "Aplikasi ini hanya untuk tujuan pendidikan dan spiritual. Konten harus diverifikasi dengan ulama Islam yang berkualifikasi.",
            "data": "Data",
            "reset_all_data": "Reset Semua Data",
            "cancel": "Batal",
            "reset": "Reset",
            "reset_warning": "Ini akan menghapus semua favorit, riwayat, dan kemajuan streak Anda. Tindakan ini tidak dapat dibatalkan.",
            "done": "Selesai",
            "select_time": "Atur Waktu",
            "share_dhikir_title": "Bagikan Dzikir",
            "copy_text": "Salin Teks",
            "share_via": "Bagikan melalui...",
            "salaam": "Salaam",
            "salaam_arabic": "السلام عليكم",
            "welcome_description": "Selamat datang di Dhikir, teman Anda untuk mengingat Allah sepanjang hari.",
            "how_are_you_feeling_title": "Bagaimana Perasaanmu?",
            "how_are_you_feeling_arabic": "كيف حالك",
            "how_are_you_feeling_description": "Beritahu kami keadaan emosi Anda, dan kami akan menampilkan dzikir yang relevan dari Quran dan Sunnah.",
            "gentle_reminders": "Pengingat Lembut",
            "gentle_reminders_arabic": "تذكير لطيف",
            "gentle_reminders_description": "Terima notifikasi hangat sepanjang hari yang menanyakan perasaan Anda.",
            "build_your_practice": "Bangun Kebiasaan Anda",
            "build_your_practice_arabic": "بناء ممارستك",
            "build_your_practice_description": "Lacak streak harian Anda, simpan favorit, dan bangun kebiasaan berdzikir yang konsisten.",
            "choose_your_language": "Pilih Bahasa Anda",
            "choose_language_description": "Pilih bahasa yang ingin Anda gunakan. Anda bisa mengubahnya kapan saja di Pengaturan.",
            "begin_your_journey": "Mulai Perjalanan Anda",
            "enable_notifications_button": "Aktifkan Notifikasi",
            "notification_denied_message": "Tidak masalah — Anda bisa mengaktifkannya nanti di Pengaturan.",
            "continue_button": "Lanjutkan",
            "skip": "Lewati",
            "previous_button": "Sebelumnya",
            "emotion_anxious": "Cemas",
            "emotion_sad": "Sedih",
            "emotion_angry": "Marah",
            "emotion_grateful": "Bersyukur",
            "emotion_hopeful": "Penuh Harapan",
            "emotion_lonely": "Kesepian",
            "emotion_overwhelmed": "Kewalahan",
            "emotion_fearful": "Takut",
            "emotion_joyful": "Gembira",
            "emotion_lost": "Tersesat",
            "emotion_anxious_desc": "Temukan kedamaian dan ketenangan",
            "emotion_sad_desc": "Cari kenyamanan dan harapan",
            "emotion_angry_desc": "Temukan ketenangan dan kesabaran",
            "emotion_grateful_desc": "Ungkapkan rasa syukur Anda",
            "emotion_hopeful_desc": "Kuatkan kepercayaan Anda",
            "emotion_lonely_desc": "Ingat kebersamaan Allah",
            "emotion_overwhelmed_desc": "Temukan kemudahan dan kelegaan",
            "emotion_fearful_desc": "Cari perlindungan dan keberanian",
            "emotion_joyful_desc": "Bagikan kebahagiaan Anda",
            "emotion_lost_desc": "Cari petunjuk dan kejelasan",
            "situation_upon_waking": "Saat Bangun",
            "situation_during_illness": "Saat Sakit",
            "situation_traveling": "Bepergian",
            "situation_facing_difficulty": "Menghadapi Kesulitan",
            "situation_before_decision": "Sebelum Keputusan",
            "situation_seeking_forgiveness": "Memohon Ampunan",
            "situation_upon_waking_desc": "Syukuri Allah untuk hari baru",
            "situation_during_illness_desc": "Mohon kesembuhan dan kesabaran",
            "situation_traveling_desc": "Perlindungan untuk perjalanan Anda",
            "situation_facing_difficulty_desc": "Kekuatan melalui kesulitan",
            "situation_before_decision_desc": "Mohon petunjuk ilahi",
            "situation_seeking_forgiveness_desc": "Kembali kepada Allah",
        ],

        .turkish: [
            "app_name": "Zikir",
            "how_are_you_feeling": "Nasıl hissediyorsun?",
            "how_i_feel": "Nasıl Hissediyorum",
            "what_im_doing": "Ne Yapıyorum",
            "day_streak": "Günlük Seri",
            "keep_going": "Devam et!",
            "tab_home": "Ana Sayfa",
            "tab_favorites": "Favoriler",
            "tab_history": "Geçmiş",
            "tab_settings": "Ayarlar",
            "translation": "Tercüme",
            "benefit": "Faydası",
            "tap_to_count": "Saymak İçin Dokun",
            "completed": "Tamamlandı!",
            "listen_to_recitation": "Tilâveti Dinle",
            "swipe_to_navigate": "Gezinmek için kaydır",
            "no_dhikirs_found": "Zikir bulunamadı",
            "go_back": "Geri Dön",
            "share_dhikir": "Zikir paylaş",
            "add_to_favorites": "Favorilere ekle",
            "remove_from_favorites": "Favorilerden kaldır",
            "of_count": "/",
            "previous": "Önceki",
            "next": "Sonraki",
            "click_or_space_to_count": "Saymak için herhangi bir yere tıklayın veya Boşluk tuşuna basın",
            "no_favorites_yet": "Henüz Favori Yok",
            "favorites_hint": "Sevdiğiniz zikirler burada görünecek.\nKaydetmek için kalp simgesine dokunun.",
            "dhikir_details": "Zikir Detayları",
            "repeat_times": "kez",
            "no_history_yet": "Henüz Geçmiş Yok",
            "history_hint": "Okuma geçmişiniz burada\ngörünecektir.",
            "clear": "Temizle",
            "clear_history": "Geçmişi Temizle",
            "clear_history_warning": "Bu, tüm okuma geçmişinizi silecektir. Bu işlem geri alınamaz.",
            "today": "Bugün",
            "yesterday": "Dün",
            "settings": "Ayarlar",
            "preferences": "Tercihler",
            "your_progress": "İlerlemeniz",
            "current_streak": "Mevcut Seri",
            "longest_streak": "En Uzun Seri",
            "total_days": "Toplam Gün",
            "notifications": "Bildirimler",
            "enable_notifications": "Bildirimleri Etkinleştir",
            "appearance": "Görünüm",
            "appearance_system": "Sistem",
            "appearance_light": "Açık",
            "appearance_dark": "Koyu",
            "feedback": "Geri Bildirim",
            "haptic_feedback": "Dokunsal Geri Bildirim",
            "translation_language": "Tercüme Dili",
            "about": "Hakkında",
            "version": "Sürüm",
            "dhikirs": "Zikirler",
            "sources": "Kaynaklar",
            "quran_and_hadith": "Kur'an ve Hadis",
            "languages": "Diller",
            "legal": "Yasal",
            "disclaimer": "Sorumluluk Reddi",
            "disclaimer_note": "Bu uygulama yalnızca eğitim ve manevi amaçlar içindir. İçerik, nitelikli İslam alimleri ile doğrulanmalıdır.",
            "data": "Veri",
            "reset_all_data": "Tüm Verileri Sıfırla",
            "cancel": "İptal",
            "reset": "Sıfırla",
            "reset_warning": "Bu, tüm favorilerinizi, geçmişinizi ve seri ilerlemenizi silecektir. Bu işlem geri alınamaz.",
            "done": "Bitti",
            "select_time": "Saat Ayarla",
            "share_dhikir_title": "Zikir Paylaş",
            "copy_text": "Metni Kopyala",
            "share_via": "Paylaş...",
            "salaam": "Selam",
            "salaam_arabic": "السلام عليكم",
            "welcome_description": "Zikir'e hoş geldiniz, gün boyunca Allah'ı anmanız için yoldaşınız.",
            "how_are_you_feeling_title": "Nasıl Hissediyorsun?",
            "how_are_you_feeling_arabic": "كيف حالك",
            "how_are_you_feeling_description": "Duygusal durumunuzu bize söyleyin, size Kur'an ve Sünnet'ten ilgili zikirleri gösterelim.",
            "gentle_reminders": "Nazik Hatırlatmalar",
            "gentle_reminders_arabic": "تذكير لطيف",
            "gentle_reminders_description": "Gün boyunca nasıl hissettiğinizi soran sıcak bildirimler alın.",
            "build_your_practice": "Alışkanlığınızı Oluşturun",
            "build_your_practice_arabic": "بناء ممارستك",
            "build_your_practice_description": "Günlük serinizi takip edin, favorileri kaydedin ve sürekli bir zikir alışkanlığı oluşturun.",
            "choose_your_language": "Dilinizi Seçin",
            "choose_language_description": "Kullanmak istediğiniz dili seçin. Bunu istediğiniz zaman Ayarlar'dan değiştirebilirsiniz.",
            "begin_your_journey": "Yolculuğunuza Başlayın",
            "enable_notifications_button": "Bildirimleri Etkinleştir",
            "notification_denied_message": "Sorun değil — bunu daha sonra Ayarlar'dan etkinleştirebilirsiniz.",
            "continue_button": "Devam",
            "skip": "Atla",
            "previous_button": "Önceki",
            "emotion_anxious": "Endişeli",
            "emotion_sad": "Üzgün",
            "emotion_angry": "Kızgın",
            "emotion_grateful": "Şükreden",
            "emotion_hopeful": "Umutlu",
            "emotion_lonely": "Yalnız",
            "emotion_overwhelmed": "Bunalmış",
            "emotion_fearful": "Korkmuş",
            "emotion_joyful": "Sevinçli",
            "emotion_lost": "Kaybolmuş",
            "emotion_anxious_desc": "Huzur ve sükûnet bul",
            "emotion_sad_desc": "Teselli ve umut ara",
            "emotion_angry_desc": "Sakinlik ve sabır bul",
            "emotion_grateful_desc": "Şükrünü ifade et",
            "emotion_hopeful_desc": "Tevekkülünü güçlendir",
            "emotion_lonely_desc": "Allah'ın beraberliğini hatırla",
            "emotion_overwhelmed_desc": "Kolaylık ve rahatlık bul",
            "emotion_fearful_desc": "Koruma ve cesaret ara",
            "emotion_joyful_desc": "Mutluluğunu paylaş",
            "emotion_lost_desc": "Hidayet ve berraklık ara",
            "situation_upon_waking": "Uyanınca",
            "situation_during_illness": "Hastalıkta",
            "situation_traveling": "Yolculukta",
            "situation_facing_difficulty": "Zorlukla Karşılaşınca",
            "situation_before_decision": "Karar Öncesi",
            "situation_seeking_forgiveness": "Tövbe Ederken",
            "situation_upon_waking_desc": "Yeni gün için Allah'a şükret",
            "situation_during_illness_desc": "Şifa ve sabır dile",
            "situation_traveling_desc": "Yolculuğun için koruma",
            "situation_facing_difficulty_desc": "Zorlukta güç",
            "situation_before_decision_desc": "İlahi rehberlik iste",
            "situation_seeking_forgiveness_desc": "Allah'a dönüş",
        ],

        .french: [
            "app_name": "Dhikir",
            "how_are_you_feeling": "Comment vous sentez-vous ?",
            "how_i_feel": "Ce que je ressens",
            "what_im_doing": "Ce que je fais",
            "day_streak": "Jours consécutifs",
            "keep_going": "Continuez !",
            "tab_home": "Accueil",
            "tab_favorites": "Favoris",
            "tab_history": "Historique",
            "tab_settings": "Paramètres",
            "translation": "Traduction",
            "benefit": "Bienfait",
            "tap_to_count": "Appuyez pour compter",
            "completed": "Terminé !",
            "listen_to_recitation": "Écouter la récitation",
            "swipe_to_navigate": "Glissez pour naviguer",
            "no_dhikirs_found": "Aucun dhikir trouvé",
            "go_back": "Retour",
            "share_dhikir": "Partager le dhikir",
            "add_to_favorites": "Ajouter aux favoris",
            "remove_from_favorites": "Retirer des favoris",
            "of_count": "sur",
            "previous": "Précédent",
            "next": "Suivant",
            "click_or_space_to_count": "Cliquez n'importe où ou appuyez sur Espace pour compter",
            "no_favorites_yet": "Pas encore de favoris",
            "favorites_hint": "Les dhikirs que vous aimez apparaîtront ici.\nAppuyez sur l'icône cœur pour les sauvegarder.",
            "dhikir_details": "Détails du dhikir",
            "repeat_times": "fois",
            "no_history_yet": "Pas encore d'historique",
            "history_hint": "Votre historique de lecture apparaîtra ici\nen explorant les dhikirs.",
            "clear": "Effacer",
            "clear_history": "Effacer l'historique",
            "clear_history_warning": "Cela supprimera tout votre historique de lecture. Cette action est irréversible.",
            "today": "Aujourd'hui",
            "yesterday": "Hier",
            "settings": "Paramètres",
            "preferences": "Préférences",
            "your_progress": "Votre progression",
            "current_streak": "Série actuelle",
            "longest_streak": "Plus longue série",
            "total_days": "Total jours",
            "notifications": "Notifications",
            "enable_notifications": "Activer les notifications",
            "appearance": "Apparence",
            "appearance_system": "Système",
            "appearance_light": "Clair",
            "appearance_dark": "Sombre",
            "feedback": "Retour",
            "haptic_feedback": "Retour haptique",
            "translation_language": "Langue de traduction",
            "about": "À propos",
            "version": "Version",
            "dhikirs": "Dhikirs",
            "sources": "Sources",
            "quran_and_hadith": "Coran et Hadith",
            "languages": "Langues",
            "legal": "Mentions légales",
            "disclaimer": "Avertissement",
            "disclaimer_note": "Cette application est uniquement à des fins éducatives et spirituelles. Le contenu doit être vérifié auprès de savants islamiques qualifiés.",
            "data": "Données",
            "reset_all_data": "Réinitialiser toutes les données",
            "cancel": "Annuler",
            "reset": "Réinitialiser",
            "reset_warning": "Cela supprimera tous vos favoris, votre historique et votre progression. Cette action est irréversible.",
            "done": "Terminé",
            "select_time": "Régler l'heure",
            "share_dhikir_title": "Partager le dhikir",
            "copy_text": "Copier le texte",
            "share_via": "Partager via...",
            "salaam": "Salaam",
            "salaam_arabic": "السلام عليكم",
            "welcome_description": "Bienvenue dans Dhikir, votre compagnon pour le rappel d'Allah tout au long de la journée.",
            "how_are_you_feeling_title": "Comment vous sentez-vous ?",
            "how_are_you_feeling_arabic": "كيف حالك",
            "how_are_you_feeling_description": "Dites-nous votre état émotionnel et nous vous montrerons des dhikirs pertinents du Coran et de la Sunna.",
            "gentle_reminders": "Rappels doux",
            "gentle_reminders_arabic": "تذكير لطيف",
            "gentle_reminders_description": "Recevez des notifications chaleureuses tout au long de la journée.",
            "build_your_practice": "Construisez votre pratique",
            "build_your_practice_arabic": "بناء ممارستك",
            "build_your_practice_description": "Suivez votre série quotidienne, sauvegardez vos favoris et construisez une habitude de dhikir.",
            "choose_your_language": "Choisissez votre langue",
            "choose_language_description": "Sélectionnez la langue que vous souhaitez utiliser. Vous pouvez la changer à tout moment dans les Réglages.",
            "begin_your_journey": "Commencez votre voyage",
            "enable_notifications_button": "Activer les notifications",
            "notification_denied_message": "Pas de souci — vous pourrez l'activer plus tard dans les Réglages.",
            "continue_button": "Continuer",
            "skip": "Passer",
            "previous_button": "Précédent",
            "emotion_anxious": "Anxieux",
            "emotion_sad": "Triste",
            "emotion_angry": "En colère",
            "emotion_grateful": "Reconnaissant",
            "emotion_hopeful": "Plein d'espoir",
            "emotion_lonely": "Seul",
            "emotion_overwhelmed": "Submergé",
            "emotion_fearful": "Effrayé",
            "emotion_joyful": "Joyeux",
            "emotion_lost": "Perdu",
            "emotion_anxious_desc": "Trouvez la paix et la sérénité",
            "emotion_sad_desc": "Cherchez le réconfort et l'espoir",
            "emotion_angry_desc": "Trouvez le calme et la patience",
            "emotion_grateful_desc": "Exprimez votre gratitude",
            "emotion_hopeful_desc": "Renforcez votre confiance",
            "emotion_lonely_desc": "Rappelez-vous la compagnie d'Allah",
            "emotion_overwhelmed_desc": "Trouvez l'aisance et le soulagement",
            "emotion_fearful_desc": "Cherchez la protection et le courage",
            "emotion_joyful_desc": "Partagez votre bonheur",
            "emotion_lost_desc": "Cherchez la guidance et la clarté",
            "situation_upon_waking": "Au réveil",
            "situation_during_illness": "Pendant la maladie",
            "situation_traveling": "En voyage",
            "situation_facing_difficulty": "Face à la difficulté",
            "situation_before_decision": "Avant une décision",
            "situation_seeking_forgiveness": "Demander pardon",
            "situation_upon_waking_desc": "Remerciez Allah pour un nouveau jour",
            "situation_during_illness_desc": "Demandez la guérison et la patience",
            "situation_traveling_desc": "Protection pour votre voyage",
            "situation_facing_difficulty_desc": "Force dans l'épreuve",
            "situation_before_decision_desc": "Demandez la guidance divine",
            "situation_seeking_forgiveness_desc": "Retour vers Allah",
        ],

        .malay: [
            "app_name": "Dhikir",
            "how_are_you_feeling": "Bagaimana perasaan anda?",
            "how_i_feel": "Perasaan Saya",
            "what_im_doing": "Apa Yang Saya Lakukan",
            "day_streak": "Hari Berturut-turut",
            "keep_going": "Teruskan!",
            "tab_home": "Utama",
            "tab_favorites": "Kegemaran",
            "tab_history": "Sejarah",
            "tab_settings": "Tetapan",
            "translation": "Terjemahan",
            "benefit": "Manfaat",
            "tap_to_count": "Ketik untuk Mengira",
            "completed": "Selesai!",
            "listen_to_recitation": "Dengar Bacaan",
            "swipe_to_navigate": "Leret untuk navigasi",
            "no_dhikirs_found": "Tiada zikir ditemui",
            "go_back": "Kembali",
            "share_dhikir": "Kongsi zikir",
            "add_to_favorites": "Tambah ke kegemaran",
            "remove_from_favorites": "Buang dari kegemaran",
            "of_count": "daripada",
            "previous": "Sebelumnya",
            "next": "Seterusnya",
            "click_or_space_to_count": "Klik di mana sahaja atau tekan Ruang untuk mengira",
            "no_favorites_yet": "Belum Ada Kegemaran",
            "favorites_hint": "Zikir kegemaran anda akan muncul di sini.\nKetik ikon hati untuk menyimpannya.",
            "dhikir_details": "Butiran Zikir",
            "repeat_times": "kali",
            "no_history_yet": "Belum Ada Sejarah",
            "history_hint": "Sejarah bacaan anda akan muncul di sini\napabila anda meneroka zikir.",
            "clear": "Padam",
            "clear_history": "Padam Sejarah",
            "clear_history_warning": "Ini akan memadam semua sejarah bacaan anda. Tindakan ini tidak boleh dibatalkan.",
            "today": "Hari Ini",
            "yesterday": "Semalam",
            "settings": "Tetapan",
            "preferences": "Keutamaan",
            "your_progress": "Kemajuan Anda",
            "current_streak": "Streak Semasa",
            "longest_streak": "Streak Terpanjang",
            "total_days": "Jumlah Hari",
            "notifications": "Pemberitahuan",
            "enable_notifications": "Aktifkan Pemberitahuan",
            "appearance": "Penampilan",
            "appearance_system": "Sistem",
            "appearance_light": "Cerah",
            "appearance_dark": "Gelap",
            "feedback": "Maklum Balas",
            "haptic_feedback": "Maklum Balas Haptik",
            "translation_language": "Bahasa Terjemahan",
            "about": "Perihal",
            "version": "Versi",
            "dhikirs": "Zikir",
            "sources": "Sumber",
            "quran_and_hadith": "Quran & Hadis",
            "languages": "Bahasa",
            "legal": "Undang-undang",
            "disclaimer": "Penafian",
            "disclaimer_note": "Aplikasi ini hanya untuk tujuan pendidikan dan kerohanian. Kandungan perlu disahkan dengan ulama Islam yang berkelayakan.",
            "data": "Data",
            "reset_all_data": "Set Semula Semua Data",
            "cancel": "Batal",
            "reset": "Set Semula",
            "reset_warning": "Ini akan memadam semua kegemaran, sejarah, dan kemajuan streak anda. Tindakan ini tidak boleh dibatalkan.",
            "done": "Selesai",
            "select_time": "Tetapkan Masa",
            "share_dhikir_title": "Kongsi Zikir",
            "copy_text": "Salin Teks",
            "share_via": "Kongsi melalui...",
            "salaam": "Salaam",
            "salaam_arabic": "السلام عليكم",
            "welcome_description": "Selamat datang ke Dhikir, teman anda untuk mengingati Allah sepanjang hari.",
            "how_are_you_feeling_title": "Bagaimana Perasaan Anda?",
            "how_are_you_feeling_arabic": "كيف حالك",
            "how_are_you_feeling_description": "Beritahu kami keadaan emosi anda, dan kami akan menunjukkan zikir yang berkaitan dari Quran dan Sunnah.",
            "gentle_reminders": "Peringatan Lembut",
            "gentle_reminders_arabic": "تذكير لطيف",
            "gentle_reminders_description": "Terima pemberitahuan yang mesra sepanjang hari yang bertanya tentang perasaan anda.",
            "build_your_practice": "Bina Amalan Anda",
            "build_your_practice_arabic": "بناء ممارستك",
            "build_your_practice_description": "Jejak streak harian anda, simpan kegemaran, dan bina tabiat zikir yang konsisten.",
            "choose_your_language": "Pilih Bahasa Anda",
            "choose_language_description": "Pilih bahasa yang anda mahu gunakan. Anda boleh menukarnya pada bila-bila masa dalam Tetapan.",
            "begin_your_journey": "Mulakan Perjalanan Anda",
            "enable_notifications_button": "Aktifkan Pemberitahuan",
            "notification_denied_message": "Tidak mengapa — anda boleh mengaktifkannya kemudian dalam Tetapan.",
            "continue_button": "Teruskan",
            "skip": "Langkau",
            "previous_button": "Sebelumnya",
            "emotion_anxious": "Cemas",
            "emotion_sad": "Sedih",
            "emotion_angry": "Marah",
            "emotion_grateful": "Bersyukur",
            "emotion_hopeful": "Penuh Harapan",
            "emotion_lonely": "Keseorangan",
            "emotion_overwhelmed": "Terbeban",
            "emotion_fearful": "Takut",
            "emotion_joyful": "Gembira",
            "emotion_lost": "Tersesat",
            "emotion_anxious_desc": "Cari kedamaian dan ketenangan",
            "emotion_sad_desc": "Cari keselesaan dan harapan",
            "emotion_angry_desc": "Cari ketenangan dan kesabaran",
            "emotion_grateful_desc": "Ungkapkan kesyukuran anda",
            "emotion_hopeful_desc": "Kuatkan kepercayaan anda",
            "emotion_lonely_desc": "Ingat kebersamaan Allah",
            "emotion_overwhelmed_desc": "Cari kemudahan dan kelegaan",
            "emotion_fearful_desc": "Cari perlindungan dan keberanian",
            "emotion_joyful_desc": "Kongsi kebahagiaan anda",
            "emotion_lost_desc": "Cari petunjuk dan kejelasan",
            "situation_upon_waking": "Ketika Bangun",
            "situation_during_illness": "Ketika Sakit",
            "situation_traveling": "Dalam Perjalanan",
            "situation_facing_difficulty": "Menghadapi Kesukaran",
            "situation_before_decision": "Sebelum Keputusan",
            "situation_seeking_forgiveness": "Memohon Keampunan",
            "situation_upon_waking_desc": "Syukur kepada Allah untuk hari baru",
            "situation_during_illness_desc": "Mohon penyembuhan dan kesabaran",
            "situation_traveling_desc": "Perlindungan untuk perjalanan anda",
            "situation_facing_difficulty_desc": "Kekuatan melalui kesukaran",
            "situation_before_decision_desc": "Mohon petunjuk ilahi",
            "situation_seeking_forgiveness_desc": "Kembali kepada Allah",
        ],
    ]

    func string(_ key: AppString, for language: SupportedLanguage) -> String {
        translations[language]?[key.rawValue]
            ?? translations[.english]?[key.rawValue]
            ?? key.rawValue
    }
}

// MARK: - Global Helper

func L(_ key: AppString, _ language: SupportedLanguage) -> String {
    LocalizationService.shared.string(key, for: language)
}
